# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
 push:
  branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: ${{github.actor}}
      run: |
       echo ${{vars.TESTENV}}
       echo test env
    - run: |
       echo "<tr><td>PING_INLINE,61716.97,64016.39,-2299.42</td></tr>" >> $GITHUB_STEP_SUMMARY
       


    

